-- ===========================================================================
-- stint9_messages — race-control message board (penalties, incidents, flags)
-- ===========================================================================
-- Source of truth is WIGE live-timing channel [3] (PID:"3" frames carrying a
-- MESSAGES:[{ID,MESSAGETIME,MESSAGE,MESSAGEGROUP}] array). The wige-scrape edge
-- function (live/wige-scrape/index.ts, driven every minute by the
-- stint9_wige_autoscan pg_cron during session windows) maps each item and
-- upserts here, deduped on ext_key. The dashboard's message board reads it with
-- the anon key; rows also snapshot into stint9_events on archive.
--
-- Messages carry NO event_date (they are global / point-in-time); the scrape
-- encodes the day into ext_key so same-text messages on different days coexist.
-- Idempotent — safe to re-run.

create table if not exists public.stint9_messages (
  id         bigint generated by default as identity primary key,
  race_class text,                     -- null = applies to all classes (feed's MESSAGEGROUP is empty)
  car        text,                     -- first car number named in the message, if any
  message    text not null,
  source     text default 'wige',      -- 'wige' = scraped; null/other = manual
  ext_key    text,                     -- '<event_date>|<MESSAGETIME>|<MESSAGE>' for scraped rows; NULL for manual
  created_at timestamptz default now() -- message time-of-day (Europe/Berlin) as a UTC instant
);

-- If the table predates ext_key, add it.
alter table public.stint9_messages add column if not exists ext_key text;

-- Dedup key for scraped rows. A plain UNIQUE index treats NULLs as distinct, so
-- unlimited manual inserts (ext_key NULL) are allowed while scraped rows dedup.
create unique index if not exists stint9_messages_ext_key_uidx
  on public.stint9_messages (ext_key);
comment on column public.stint9_messages.ext_key is
  'Dedup key for scraped race-control msgs: <event_date>|<MESSAGETIME>|<MESSAGE>. NULL for manual inserts.';

-- RLS: the board is public (read + insert with the anon/publishable key).
alter table public.stint9_messages enable row level security;
drop policy if exists "public can read messages"   on public.stint9_messages;
drop policy if exists "public can insert messages" on public.stint9_messages;
create policy "public can read messages"   on public.stint9_messages for select using (true);
create policy "public can insert messages" on public.stint9_messages for insert with check (true);
